# Generated by Django 5.0.2 on 2024-02-28 08:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelompok', '0001_initial'),
        ('mahasiswa', '0006_mentee'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentoringSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('attendees', models.ManyToManyField(blank=True, related_name='attended_sessions', to='mahasiswa.mentee')),
                ('kelompok', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentoring_sessions', to='kelompok.kelompok')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
