POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
    "username": "keiradiaz",
    "email": "keira@mail.com",
    "password": "bismillahgacor",
    "npm": "2306256394"
}


POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "keiradiaz",
    "password": "bismillahgacor"
}


POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "admin",
    "password": "admin"
}


POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
    "username": "reiner",
    "email": "rein@mail.com",
    "password": "pppgacor",
    "npm": "2206025211"
}


POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "reiner",
    "password": "pppgacor"
}


GET http://localhost:8000/api/bidang/
Content-Type: application/json
Authorization: Token 451bc553be0e4e303ecf313f3246807962c71d0a

{
    "username": "<insert username>",
    "email": "<insert email>",
    "password": '"<insert password>",
    ""
}