POST http://localhost:8000/api/auth/register/
Content-Type: application/json

{
    "username": "keiradiaz",
    "email": "keira@mail.com",
    "password": "bismillahgacor",
    "npm": "2306256394"
}



POST http://localhost:8000/api/auth/login/
Content-Type: application/json

{
    "username": "keiradiaz",
    "password": "bismillahgacor"
}