# Generated by Django 5.0.2 on 2024-02-29 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acara', '0002_pembicara_sponsor_pembicaraacara_sponsoracara'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sponsoracara',
            unique_together={('sponsor', 'acara')},
        ),
    ]
