# Generated by Django 5.0.2 on 2024-02-29 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acara', '0003_alter_sponsoracara_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='acara',
            name='pembicara_list',
            field=models.ManyToManyField(to='acara.pembicara'),
        ),
        migrations.AddField(
            model_name='acara',
            name='sponsor_list',
            field=models.ManyToManyField(through='acara.SponsorAcara', to='acara.sponsor'),
        ),
        migrations.DeleteModel(
            name='PembicaraAcara',
        ),
    ]
