# Generated by Django 5.0.2 on 2024-02-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acara', '0004_acara_pembicara_list_acara_sponsor_list_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acara',
            name='pembicara_list',
            field=models.ManyToManyField(related_name='mengisi', to='acara.pembicara'),
        ),
    ]
