# Generated by Django 5.0.2 on 2024-02-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='npm',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
