# Generated by Django 5.0.2 on 2024-02-26 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0002_alter_mahasiswa_npm'),
        ('okk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahasiswa',
            name='fakultas',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='okk.fakultas'),
        ),
    ]
