# Generated by Django 5.0.2 on 2024-02-27 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kelompok', '0001_initial'),
        ('mahasiswa', '0003_alter_mahasiswa_fakultas'),
        ('organisasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mentor',
            name='kelompok',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='kelompok.kelompok'),
        ),
        migrations.AlterField(
            model_name='panitia',
            name='bidang',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='organisasi.bidangkepanitiaan'),
        ),
    ]
