# Generated by Django 5.0.2 on 2024-02-28 00:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0004_alter_mentor_kelompok_alter_panitia_bidang'),
        ('organisasi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panitia',
            name='bidang',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisasi.bidangkepanitiaan'),
        ),
    ]
