# Generated by Django 5.0.2 on 2024-02-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mahasiswa', '0006_mentee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='panitia',
            name='jabatan',
            field=models.CharField(choices=[('PI', 'Pengurus Inti'), ('BPH-PJ', 'BPH - Penanggung Jawab'), ('BPH-WAPJ', 'BPH - Wakil Penanggung Jawab'), ('STAFF', 'Staff')], max_length=200),
        ),
    ]
